graceful:
  shutdown.enabled: false

oauth:
  endpoint.url: http://localhost:8090/auth

aws:
  provider: localstack

sns:
  topic:
    arn: arn:aws:sns:eu-west-2:000000000000:hmpps_domain_events

  endpoint:
    url: http://localhost:4575

spring:
  datasource:
    url: 'jdbc:h2:mem:court-register-db;MODE=PostgreSQL'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true