---
# Values here are the same across all environments
generic-service:
  nameOverride: court-register

  image:
    repository: quay.io/hmpps/court-register
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /prometheus {
          deny all;
          return 401;
        }
    tlsSecretName: court-register-cert

  serviceAccountName: hmpps-registers

  env:
    SERVER_PORT: 8080
    JAVA_OPTS: "-Xmx512m"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    HMPPS_SQS_USE_WEB_TOKEN: true

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    court-register:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    dps-rds-instance-output:
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "sqs_queue_name"

generic-prometheus-alerts:
  targetApplication: court-register
