---
# Environment specific values, override helm_deploy/court-register/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: court-register.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
  rdsAlertsDatabases:
    cloud-platform-28d4422ea8c4e982: 'court register'
