---
# Environment specific values, override helm_deploy/court-register/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: court-register-preprod.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
  rdsAlertsDatabases:
    cloud-platform-4766e13668250cc5: 'court register'
