UPDATE COURT SET COURT_TYPE = 'MAGISTRATES' WHERE COURT_TYPE = 'Magistrates Court';
UPDATE COURT SET COURT_TYPE = 'CROWN' WHERE COURT_TYPE = 'Crown Court';
UPDATE COURT SET COURT_TYPE = 'COUNTY' WHERE COURT_TYPE = 'County Court';
UPDATE COURT SET COURT_TYPE = 'YOUTH' WHERE COURT_TYPE = 'Youth Court';
UPDATE COURT SET COURT_TYPE = 'OTHER' WHERE COURT_TYPE = 'Other';
UPDATE COURT SET COURT_TYPE = 'SHERRIFS_SCOTTISH' WHERE COURT_TYPE = 'Sherrifs Court (Scottish)';
UPDATE COURT SET COURT_TYPE = 'ASYLUM_IMMIGRATION' WHERE COURT_TYPE = 'Asylum and Immigration Tribunal';
UPDATE COURT SET COURT_TYPE = 'IMMIGRATION' WHERE COURT_TYPE = 'Immigration';
UPDATE COURT SET COURT_TYPE = 'COURTS_MARTIAL' WHERE COURT_TYPE = 'Courts Martial';
UPDATE COURT SET COURT_TYPE = 'DISTRICT_SCOTTISH' WHERE COURT_TYPE = 'District Court (Scottish)';
UPDATE COURT SET COURT_TYPE = 'OUTSIDE_ENG_WALES' WHERE COURT_TYPE = 'Court outside England/Wales';
UPDATE COURT SET COURT_TYPE = 'APPEAL' WHERE COURT_TYPE = 'Court Of Appeal Criminal Division';
UPDATE COURT SET COURT_TYPE = 'HIGH_COURT_SCOTTISH' WHERE COURT_TYPE = 'High Court (Scottish)';



